### ISSUE TITLE
老哥，支持你

### ISSUE THREAD

**Issue by netnr** [ldqk/Masuit.LuceneEFCore.SearchEngine#1]
交流一下我的一些想法：
在实体上标注特性值，这个面临一个问题：生成实体，一般会用 `Scaffold-DbContext` 命令自动生成，更新就很麻烦，暂时想到就是把这个独立一个项目，然后增加一个任务队列（表）并开放接口，定时处理队列需要更新的项，而应用程序全部提交到任务队列中

**Comment by netnr** [comment]
能提供分类搜索接口吗，比如
![image](https://user-images.githubusercontent.com/10579621/65485487-9bcf5500-ded4-11e9-80fd-dd4a195b0f80.png)

在某个类别下检索

**Comment by ldqk** [comment]
如果有这样既有精确搜索又有模糊查询的，我觉得应该要在全文检索前，先传一个Expression做一个精确查询，再把结果进行模糊检索，有时间再研究完善一下吧
