### ISSUE TITLE
有什么方式可以实现自定义条件来搜索的。

### ISSUE THREAD

**Issue by qcjxberin** [ldqk/Masuit.LuceneEFCore.SearchEngine#10]
有什么方式可以实现自定义条件来搜索的。比如我某个实体里有个字段为布尔值或者是整形，搜索的时候是否可以指定某值搜索的条件为布尔值或者是整形的，这样就可以对一个表里的数据做区分搜索。

**Comment by ldqk** [comment]
这种需求建议使用数据库查询就好了，根本不需要全文检索

**Comment by qcjxberin** [comment]
需要全文检索吧，因为还是有搜索关键词啊，只不过会另外有一个条件。

**Comment by ldqk** [comment]
这种情况你应该在创建索引的时候就只创建符合条件的数据的索引

**Comment by ldqk** [comment]
示例代码：https://github.com/ldqk/Masuit.MyBlogs/blob/3c37e648f658b8e1d14ab0ee6cd8c98e00e99921/src/Masuit.MyBlogs.Core/Extensions/Hangfire/HangfireBackJob.cs#L249

**Comment by hyfree** [comment]
建议使用过滤filter

**Comment by ldqk** [comment]
什么意思？

**Comment by ldqk** [comment]
如果你有什么好的改进或想法，直接提pr吧

**Comment by hyfree** [comment]
可以看#13

**Comment by hyfree** [comment]
> 可以看#13

https://www.cnblogs.com/qingyibusi/p/6235856.html
也算一个解决办法

**Comment by qcjxberin** [comment]
@hyfree 你有试过多表不同实体的数据进行过滤吗？
