### ISSUE TITLE
如何让搜索关键词的分词权重最高的，

### ISSUE THREAD

**Issue by qcjxberin** [ldqk/Masuit.LuceneEFCore.SearchEngine#11]
如何让搜索关键词的分词权重最高的，目前测试发现内容里有匹配到搜索关键词，但是仍然给拆分了。

**Comment by qcjxberin** [comment]
主要是在高亮那一块。

**Comment by ldqk** [comment]
这个需要你做你的自定义词库，在应用程序启动之初就导入自定义词库就好了，比如：
![image](https://user-images.githubusercontent.com/20254980/119229133-0c66c300-bb49-11eb-9b84-dbd5f3a8c099.png)

**Comment by qcjxberin** [comment]
有导入自定义词库

**Comment by ldqk** [comment]
这就得优化你的词库了
