### ISSUE TITLE
示例似乎按照搜索不到大多数关键字

### ISSUE THREAD

**Issue by charset** [ldqk/Masuit.LuceneEFCore.SearchEngine#12]
代码co下来以后仅在Startup里面添加了
searchEngine.SaveChanges();
然后用/Home/Index?s=
来搜索似乎一些常用的关键字都搜不到。目前对照了发现Title和Keywords这两个里面的可以搜到。Content试了一些无法搜到。
![image](https://user-images.githubusercontent.com/1499849/127120378-04e33f74-9e0c-4007-b8ce-d881e9be37c4.png)
![image](https://user-images.githubusercontent.com/1499849/127120446-c0cf9bbe-b7b2-4e89-993d-d2a11c6b820b.png)

**Comment by ldqk** [comment]
需要做自己的词库啊，亲！

**Comment by charset** [comment]
Sorry，以为是All-In-One的解决方案哈……

**Comment by ldqk** [comment]
这只是个简单的搜索引擎组件，是需要做自己的词库才能按预期结果搜索的，并没有人工智能(人工智障)的成分在里面

**Comment by ldqk** [comment]
All-In-One的解决方案直接上ES！

**Comment by charset** [comment]
亲，能教一下如何配置Dict.dct, stopwords的路径？似乎只找到了asp.net和winform的配置方法。

**Comment by ldqk** [comment]
参考最佳实践： https://github.com/ldqk/Masuit.MyBlogs/blob/71e043822009dc977e4ccfbc6f8450948f23be4a/src/Masuit.MyBlogs.Core/PrepareStartup.cs#L57

**Comment by charset** [comment]
谢谢，找到原因了。
