### ISSUE TITLE
问题:如果增加过滤

### ISSUE THREAD

**Issue by hyfree** [ldqk/Masuit.LuceneEFCore.SearchEngine#13]
场景:
网站拥有多个用户，每个用户只可以搜索自己的内容，并且可以选择搜索全部文章或者已经发布的文章
是否可以在searchoption类里面增加Filter,indexer搜索的时候传入filter(现在代码里面的是null)或者其他方式来过滤。
另外，这样做是否存在性能问题

**Comment by ldqk** [comment]
已支持，更新最新版本即可

**Comment by qcjxberin** [comment]
具体怎么使用的？

**Comment by ldqk** [comment]
searchoption的Filter属性

**Comment by qcjxberin** [comment]
能不能弄个简单的教程的？或者一些用法代码，这样更直接一些。

**Comment by ldqk** [comment]
searchoption的Filter属性暴露的是Lucene底层的类型，具体参考lucene的文档即可，这里不需要重复搬运文档

**Comment by qcjxberin** [comment]
有什么工具可以看lucene生成的内容吗？

**Comment by hyfree** [comment]
lucene的文档请看这里：

https://lucenenet.apache.org/docs/4.8.0-beta00016/api/queries/Lucene.Net.Queries.html

或者博客

https://blog.csdn.net/csmnjk/article/details/51964931
https://www.cnblogs.com/zjoch/p/4467909.html


lucene 也允许你使用多个表达式，表示a&b的概念（适用场景：只全文搜索某个用户或者时间范围内的文章），具体请看lucene的文档。
https://cn.bing.com/search?q=Lucene.Net+Query

https://cn.bing.com/search?q=Lucene.Net++Filter

**Comment by qcjxberin** [comment]
如果搜索某用户的话，是不是这个用户字段的值也得配置为支持Lunce的？

**Comment by qcjxberin** [comment]
另外如果是多个表，那是否有什么合适的方法直接通过表的实体来做为过滤条件的？
