### ISSUE TITLE
请问下支持导航属性下的搜索吗

### ISSUE THREAD

**Issue by xjn19940305** [ldqk/Masuit.LuceneEFCore.SearchEngine#14]
比如我这边有个Course课程表 有个Expert专家表 还有个CourseExpert课程专家关联表，
平时读数据可以通过EFCORE导航属性读出来，但是搜索的时候想搜专家然后把课程课程专家以及专家数据以导航属性搜索出来可以做到吗？

**Comment by ldqk** [comment]
抱歉，不可以，这个库只支持单表的检索，关联查询的复杂场景建议使用ElasticSearch，或者使用正则表达式进行数据库查询
