### ISSUE TITLE
在Controller中注入ILuceneIndexer并搜索两次可以触发Exception

### ISSUE THREAD

**Issue by rabbitism** [ldqk/Masuit.LuceneEFCore.SearchEngine#15]
复现方法：将HomeController代码替换为示例文档的代码并进行两次搜索。
原因：Lucene打开Directory失败。

暂时解决方案：不注入ILuceneIndexer，直接使用SearchEngine的LuceneIndexer

**Comment by ldqk** [comment]
LuceneIndexer里面把Directory和Analyzer这两个单例对象dispose导致的bug，已修正，更新最新包即可。
