### ISSUE TITLE
建议及问题

### ISSUE THREAD

**Issue by angelxg** [ldqk/Masuit.LuceneEFCore.SearchEngine#2]
示例代码 Startup里面
            db.Post.AddRange(JsonConvert.DeserializeObject<List<Post>>(File.ReadAllText(AppContext.BaseDirectory + "Posts.json")));
           后面是不是要加个提交 才行  我的是这样才好用 db.SaveChanges();

搜索后结果 是否有高亮显示功能 用这个  Lucene.Net.Search.Highlight

最后 我用Abp框架集成的时候  报错 也没细研究

谢谢

**Comment by ldqk** [comment]
示例代码里面是基于内存的数据库做演示的，所以不需要db.SaveChanges();
另外报错的话能否提供下详细的堆栈信息，这样才好定位问题，做相关的修复。

**Comment by angelxg** [comment]
我是直接下载示例代码 然后 Post表初始化 Json那些数据就没有进去，然后 加了个SaveChanges就好了 不知道是不是EF版本 问题

错误应该是 Startup 的 Config方法  对象初始化注入失败

System.Exception: 'Could not resolve a service of type 'Masuit.LuceneEFCore.SearchEngine.Interfaces.ISearchEngine`1[[iProcurementPortal.EntityFrameworkCore.LuceneDataContext, iProcurementPortal.EntityFrameworkCore, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]' for the parameter 'searchEngine' of method 'Configure' on type 'iProcurementPortal.Web.Host.Startup.Startup'.'


This exception was originally thrown at this call stack:
	Castle.MicroKernel.Handlers.DefaultHandler.AssertNotWaitingForDependency()
	Castle.MicroKernel.Handlers.DefaultHandler.ResolveCore(Castle.MicroKernel.Context.CreationContext, bool, bool, out Castle.MicroKernel.Burden)
	Castle.MicroKernel.Handlers.DefaultHandler.Resolve(Castle.MicroKernel.Context.CreationContext, bool)
	Castle.MicroKernel.Handlers.AbstractHandler.Resolve(Castle.MicroKernel.Context.CreationContext)
	Castle.MicroKernel.Handlers.DefaultGenericHandler.Resolve(Castle.MicroKernel.Context.CreationContext, bool)
	Castle.MicroKernel.Handlers.AbstractHandler.Resolve(Castle.MicroKernel.Context.CreationContext)
	Castle.MicroKernel.DefaultKernel.ResolveComponent(Castle.MicroKernel.IHandler, System.Type, Castle.MicroKernel.Arguments, Castle.MicroKernel.IReleasePolicy, bool)
	Castle.MicroKernel.DefaultKernel.Castle.MicroKernel.IKernelInternal.Resolve(System.Type, Castle.MicroKernel.Arguments, Castle.MicroKernel.IReleasePolicy, bool)
	Castle.MicroKernel.DefaultKernel.Resolve(System.Type, Castle.MicroKernel.Arguments)
	Castle.Windsor.WindsorContainer.Resolve(System.Type)
    ...
    [Call Stack Truncated]

**Comment by angelxg** [comment]
另外 是否可以封装一些 类似SQL的 方法
比如 sql IN(exists) 的
还有时间或者 数值 范围 
我的业务场景 比较类似 淘宝 搜索商品 +  过滤筛选

**Comment by ldqk** [comment]
这个看上去应该是没有正确配置依赖注入导致的；
另外，这只是一个简单的全文检索库封装，搜索加筛选这种的，还是需要ElasticSearch这样的专业组件才行。
