### ISSUE TITLE
支持自定义实体么

### ISSUE THREAD

**Issue by shenglingshi** [ldqk/Masuit.LuceneEFCore.SearchEngine#22]
是否支持不使用数据库实体，而使用自定义的聚合实体。有的查询关键词会涉及多个表里的多个字段。需要聚合为一个实体作为结果返回。

**Comment by ldqk** [comment]
这种情况你通过二次查询就可以实现了，利用搜索引擎的结果作为数据库查询的条件就行了，比如你通过关键词xxx搜索到id为1,3,4,5,8的结果，然后你再用这几个id作为数据库查询的条件，就实现了
